sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t parth731/learn-jenkins-docker-app -f Dockerfile.dev .

script:
  - docker run -e CI=true parth731/learn-jenkins-docker-app npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  env: "docker-env-1"
  bucket_name: "elasticbeanstalk-ap-south-1-597081897916"
  bucket_path: "docker"
  on:
    branch: master
